//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SekmesRatas.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SekmesRatas.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ar tikrai norite istrinti elementa/us?.
        /// </summary>
        internal static string str_ar_tikrai {
            get {
                return ResourceManager.GetString("str_ar_tikrai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pridekite bent 2 elementus.
        /// </summary>
        internal static string str_bent_2_elem {
            get {
                return ResourceManager.GetString("str_bent_2_elem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daugiau elementu negalima prideti arba neivedet reiksmes.
        /// </summary>
        internal static string str_daugiau_negalima {
            get {
                return ResourceManager.GetString("str_daugiau_negalima", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demesio.
        /// </summary>
        internal static string str_demesio {
            get {
                return ResourceManager.GetString("str_demesio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to asdasdasdjkasdfaaaaaaaaaaaaaaa\
        ///naaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa.
        /// </summary>
        internal static string str_helpas {
            get {
                return ResourceManager.GetString("str_helpas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nepasirinkote elemento.
        /// </summary>
        internal static string str_nepasirinktas_elem {
            get {
                return ResourceManager.GetString("str_nepasirinktas_elem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pagalba.
        /// </summary>
        internal static string str_pagalba {
            get {
                return ResourceManager.GetString("str_pagalba", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bandykite dar karta.
        /// </summary>
        internal static string str_try_again {
            get {
                return ResourceManager.GetString("str_try_again", resourceCulture);
            }
        }
    }
}
